name: Sync Med Data
on:
  schedule:
    - cron: '*/30 * * * *' # تحديث كل 30 دقيقة
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch and Save Data
        run: |
          pip install pandas requests
          python3 -c "
          import pandas as pd
          url = 'https://docs.google.com/spreadsheets/d/1M7WLnM9Dgbz-fzpoJmbW3DSC9Z-apul8qMD0mJjmB1U/gviz/tq?tqx=out:csv&sheet=Sheet2'
          df = pd.read_csv(url)
          df.columns = df.columns.str.strip()
          df.to_json('data.json', orient='records', force_ascii=False)
          "

      - name: Commit changes
        run: |
          git config --global user.name 'DataBot'
          git config --global user.email 'bot@github.com'
          git add data.json
          git commit -m 'تحديث تلقائي للمخزون' || exit 0
          git push
